{% set version = "2.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcdklibs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rcdklibs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rcdklibs/rcdklibs_{{ version }}.tar.gz
  sha256: ef91ad0411f35c5bafcec03b986c8bab99782b7be858a86d944877308ab1b4c1

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjava >=0.9_8
  run:
    - r-base
    - r-rjava >=0.9_8

test:
  commands:
    - $R -e "library('rcdklibs')"           # [not win]
    - "\"%R%\" -e \"library('rcdklibs')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rcdklibs
  license: LGPL
  summary: An R interface to the Chemistry Development Kit, a Java library for chemoinformatics. Given the size of the library itself, this package is not expected to change very frequently. To make use of the CDK within R, it is suggested that you use the 'rcdk' package. Note that it is possible to directly interact with
    the CDK using 'rJava'. However 'rcdk' exposes functionality in a more idiomatic way. The CDK library itself is released as LGPL and the sources can be obtained from <https://github.com/cdk/cdk>.
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rcdklibs
# Version: 2.0
# Date: 2017-06-10
# Authors@R: c(person('Rajarshi', 'Guha', role=c('aut'), email='rajarshi.guha@gmail.com'), person('Zachary', 'Charlop-Powers', role=c('cre'), email='zach.charlop.powers@gmail.com'), person('CDK Project', '', role=c('ctb', 'cph'), comment='CDK Java library contained in multiple jar files'))
# Depends: R (>= 2.0.0), rJava (>= 0.9-8)
# License: LGPL
# Title: The CDK Libraries Packaged for R
# Description: An R interface to the Chemistry Development Kit, a Java library for chemoinformatics. Given the size of the library itself, this package is not expected to change very frequently. To make use of the CDK within R, it is suggested that you use the 'rcdk' package. Note that it is possible to directly interact with the CDK using 'rJava'. However 'rcdk' exposes functionality in a more idiomatic way. The CDK library itself is released as LGPL and the sources can be obtained from <https://github.com/cdk/cdk>.
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2017-06-10 14:29:54 UTC; zachpowers
# Author: Rajarshi Guha [aut], Zachary Charlop-Powers [cre], CDK Project [ctb, cph] (CDK Java library contained in multiple jar files)
# Maintainer: Zachary Charlop-Powers <zach.charlop.powers@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-06-11 07:39:03 UTC
