travis:
  secure:
    BINSTAR_TOKEN: jQ2Zm92oZ7UpUxEiSXnI6gps7ygrZ2g7sWKUNlwzY/PZqKa8X3SGxuoMM38Eo7K+AczZhk+P2R9brKtSLhcXQkl9tOpfoD1RvmC4IJE9xuk89FHUpVGvk7+DGl8TlxGsath+/amvbB9Q4o4SFekEbwKpQHeCLgSpp4N2w3s27WWtaNkHO2jm/SqEiy3LXzhatnDN752wmGIHW6UoRR8Z8IbBcOJfC2J7zaD1NfsN9Ez0Z9gOsTB1+wqjdiF43O9cVyZB9Qd0oS9LekAsiPr36A3S3UaYRKtOJ4elUVO3ex2CW2txWJmvyLh7KlcZfe3kc0ztqJzi3B9DkZnzKat83PbqsADk4jF4gQjEPLiYTxYlSXy9kCTdlPP9ilNaD0eLizgXA0HnWkXLQxq7M9DDQlr3ZlmHgUQ0184N3U9k25pzOw0VEAXxvvt6Ky7jAw1DIRsiboEFkRcE0A7qu1oWQ3rh1eOw7GG6tn5t1YuRtyTwOrIOthSn4GFLMrqiFHkwaGJgD553PquNc0bgsx63/vc9A36MGjuXESuztM6kDzV9hHQ2LxtDd3b0XGRE37uahA+HwAeO5jWFW10boqxS/kimxwHE6hJAS0MDtAhNintlyWH9fgrAcN2yWJfsI/5M+PKgEB8bX8wRfKYJkCP7KZner2bWckBeZBfjXS6J3lw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
